using Api.Dtos.Requests.VoucherDefinitions;
using Api.Validators.VoucherDefinitions;
using Core.Entities.Constants;
using FluentValidation.TestHelper;

namespace Api.Tests.Validators.VoucherDefinitions;

public sealed class VoucherDefinitionRequestDtoValidatorTests
{
    private readonly CreateVoucherDefinitionRequestDtoValidator _createValidator = new();

    [Fact]
    public void Create_ValidPublicFixedVoucher_HasNoErrors()
    {
        var request = ValidPublicFixedRequest();

        var result = _createValidator.TestValidate(request);

        result.ShouldNotHaveAnyValidationErrors();
    }

    [Fact]
    public void Create_ValidPrivateDynamicVoucher_HasNoErrors()
    {
        var request = new CreateVoucherDefinitionRequestDto
        {
            Code = null,
            Name = "Private voucher",
            RewardType = VoucherRewardTypes.Percent,
            RewardValue = 10,
            ValidityType = VoucherValidityTypes.Dynamic,
            ValidFrom = new DateTime(2026, 1, 1),
            DurationDay = 30,
            GenerationType = VoucherGenerationTypes.AutoGenerated,
            PublishType = VoucherPublishTypes.Private,
            TotalStock = 100
        };

        var result = _createValidator.TestValidate(request);

        result.ShouldNotHaveAnyValidationErrors();
    }

    [Fact]
    public void Create_MissingRequiredTypes_ReturnsCamelCaseErrors()
    {
        var request = new CreateVoucherDefinitionRequestDto();

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("name")
            .WithErrorCode("VOUCHER_DEFINITION_NAME_REQUIRED");
        result.ShouldHaveValidationErrorFor("rewardType")
            .WithErrorCode("VOUCHER_REWARD_TYPE_REQUIRED");
        result.ShouldHaveValidationErrorFor("validityType")
            .WithErrorCode("VOUCHER_VALIDITY_TYPE_REQUIRED");
        result.ShouldHaveValidationErrorFor("generationType")
            .WithErrorCode("VOUCHER_GENERATION_TYPE_REQUIRED");
        result.ShouldHaveValidationErrorFor("publishType")
            .WithErrorCode("VOUCHER_PUBLISH_TYPE_REQUIRED");
    }

    [Fact]
    public void Create_PublicVoucherWithoutCode_ReturnsCodeRequiredError()
    {
        var request = ValidPublicFixedRequest();
        request.Code = null;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("code").WithErrorCode("VOUCHER_CODE_REQUIRED");
    }

    [Fact]
    public void Create_PrivateVoucherWithCode_ReturnsCodeMustBeEmptyError()
    {
        var request = ValidPublicFixedRequest();
        request.PublishType = VoucherPublishTypes.Private;
        request.GenerationType = VoucherGenerationTypes.Imported;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("code")
            .WithErrorCode("VOUCHER_CODE_MUST_BE_EMPTY");
    }

    [Theory]
    [InlineData(VoucherPublishTypes.Public, VoucherGenerationTypes.Imported,
        "VOUCHER_PUBLIC_GENERATION_TYPE_INVALID")]
    [InlineData(VoucherPublishTypes.Private, VoucherGenerationTypes.None,
        "VOUCHER_PRIVATE_GENERATION_TYPE_INVALID")]
    public void Create_InvalidPublishAndGenerationCombination_ReturnsExpectedError(
        string publishType,
        string generationType,
        string errorCode)
    {
        var request = ValidPublicFixedRequest();
        request.PublishType = publishType;
        request.GenerationType = generationType;
        request.Code = publishType == VoucherPublishTypes.Public ? "PUBLIC-CODE" : null;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("generationType").WithErrorCode(errorCode);
    }

    [Fact]
    public void Create_GiftVoucherWithRewardValue_ReturnsRewardValueMustBeEmptyError()
    {
        var request = ValidPublicFixedRequest();
        request.RewardType = VoucherRewardTypes.Gift;
        request.RewardValue = 10;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("rewardValue")
            .WithErrorCode("VOUCHER_REWARD_VALUE_MUST_BE_EMPTY");
    }

    [Fact]
    public void Create_FixedValidityWithoutDates_ReturnsRequiredErrors()
    {
        var request = ValidPublicFixedRequest();
        request.ValidFrom = null;
        request.ValidTo = null;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("validFrom")
            .WithErrorCode("VOUCHER_FIXED_VALIDITY_REQUIRED");
        result.ShouldHaveValidationErrorFor("validTo")
            .WithErrorCode("VOUCHER_FIXED_VALIDITY_REQUIRED");
    }

    [Fact]
    public void Create_FixedValidityWithInvalidRange_ReturnsRangeError()
    {
        var request = ValidPublicFixedRequest();
        request.ValidTo = request.ValidFrom;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("validTo")
            .WithErrorCode("VOUCHER_VALIDITY_RANGE_INVALID");
    }

    [Fact]
    public void Create_DynamicValidityWithoutDuration_ReturnsRequiredError()
    {
        var request = ValidPublicFixedRequest();
        request.ValidityType = VoucherValidityTypes.Dynamic;
        request.ValidTo = null;
        request.DurationDay = null;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("durationDay")
            .WithErrorCode("VOUCHER_DYNAMIC_VALIDITY_REQUIRED");
    }

    [Fact]
    public void Create_NegativeStock_ReturnsStockError()
    {
        var request = ValidPublicFixedRequest();
        request.TotalStock = -1;

        var result = _createValidator.TestValidate(request);

        result.ShouldHaveValidationErrorFor("totalStock")
            .WithErrorCode("VOUCHER_TOTAL_STOCK_INVALID");
    }

    [Fact]
    public void GetPaged_InvalidPagingAndKeyword_ReturnExpectedErrors()
    {
        var request = new GetVoucherDefinitionsRequestDto
        {
            Page = 0,
            PageSize = 101,
            Keyword = new string('a', 101)
        };

        var result = new GetVoucherDefinitionsRequestDtoValidator().TestValidate(request);

        result.ShouldHaveValidationErrorFor("page").WithErrorCode("PAGE_INVALID");
        result.ShouldHaveValidationErrorFor("pageSize").WithErrorCode("PAGE_SIZE_INVALID");
        result.ShouldHaveValidationErrorFor("keyword").WithErrorCode("KEYWORD_TOO_LONG");
    }

    private static CreateVoucherDefinitionRequestDto ValidPublicFixedRequest() => new()
    {
        Code = "WELCOME10",
        Name = "Welcome voucher",
        RewardType = VoucherRewardTypes.Fixed,
        RewardValue = 10,
        ValidityType = VoucherValidityTypes.Fixed,
        ValidFrom = new DateTime(2026, 1, 1),
        ValidTo = new DateTime(2026, 12, 31),
        GenerationType = VoucherGenerationTypes.None,
        PublishType = VoucherPublishTypes.Public,
        TotalStock = 100
    };
}
