using Core.Entities;
using Core.Entities.Constants;
using Core.Exceptions;
using FluentAssertions;

namespace Core.Tests.Entities;

public sealed class VoucherDefinitionTests
{
    [Fact]
    public void Create_ValidPublicVoucher_NormalizesValuesAndGeneratesState()
    {
        var before = DateTime.UtcNow;

        var voucher = CreatePublicVoucher();

        voucher.VoucherDefinitionId.Should().NotBe(Guid.Empty);
        voucher.Code.Should().Be("WELCOME10");
        voucher.Name.Should().Be("Welcome voucher");
        voucher.Description.Should().Be("Description");
        voucher.RewardType.Should().Be(VoucherRewardTypes.Fixed);
        voucher.ValidityType.Should().Be(VoucherValidityTypes.Fixed);
        voucher.GenerationType.Should().Be(VoucherGenerationTypes.None);
        voucher.PublishType.Should().Be(VoucherPublishTypes.Public);
        voucher.RemainingStock.Should().Be(voucher.TotalStock);
        voucher.CreatedAt.Should().BeOnOrAfter(before);
        voucher.DeletedAt.Should().BeNull();
    }

    [Fact]
    public void Create_ValidPrivateDynamicVoucher_HasNoCode()
    {
        var voucher = VoucherDefinition.Create(
            null,
            "Private voucher",
            null,
            null,
            VoucherRewardTypes.Percent,
            10,
            VoucherValidityTypes.Dynamic,
            DateTime.UtcNow,
            null,
            30,
            VoucherGenerationTypes.AutoGenerated,
            VoucherPublishTypes.Private,
            50);

        voucher.Code.Should().BeNull();
        voucher.DurationDay.Should().Be(30);
        voucher.RemainingStock.Should().Be(50);
    }

    [Theory]
    [InlineData(VoucherPublishTypes.Public, VoucherGenerationTypes.Imported,
        "VOUCHER_PUBLIC_GENERATION_TYPE_INVALID")]
    [InlineData(VoucherPublishTypes.Private, VoucherGenerationTypes.None,
        "VOUCHER_PRIVATE_GENERATION_TYPE_INVALID")]
    public void Create_InvalidPublishGenerationCombination_ThrowsDomainException(
        string publishType,
        string generationType,
        string expectedCode)
    {
        var action = () => VoucherDefinition.Create(
            publishType == VoucherPublishTypes.Public ? "CODE" : null,
            "Voucher",
            null,
            null,
            VoucherRewardTypes.Fixed,
            10,
            VoucherValidityTypes.Fixed,
            DateTime.UtcNow,
            DateTime.UtcNow.AddDays(1),
            null,
            generationType,
            publishType,
            10);

        action.Should().Throw<DomainException>().Which.ErrorCode.Should().Be(expectedCode);
    }

    [Fact]
    public void Create_GiftVoucherWithRewardValue_ThrowsDomainException()
    {
        var action = () => VoucherDefinition.Create(
            "GIFT",
            "Gift voucher",
            null,
            null,
            VoucherRewardTypes.Gift,
            10,
            VoucherValidityTypes.Fixed,
            DateTime.UtcNow,
            DateTime.UtcNow.AddDays(1),
            null,
            VoucherGenerationTypes.None,
            VoucherPublishTypes.Public,
            10);

        action.Should().Throw<DomainException>().Which.ErrorCode
            .Should().Be("VOUCHER_REWARD_VALUE_MUST_BE_EMPTY");
    }

    [Fact]
    public void Create_InvalidFixedDateRange_ThrowsDomainException()
    {
        var instant = DateTime.UtcNow;

        var action = () => VoucherDefinition.Create(
            "CODE",
            "Voucher",
            null,
            null,
            VoucherRewardTypes.Fixed,
            10,
            VoucherValidityTypes.Fixed,
            instant,
            instant,
            null,
            VoucherGenerationTypes.None,
            VoucherPublishTypes.Public,
            10);

        action.Should().Throw<DomainException>().Which.ErrorCode
            .Should().Be("VOUCHER_VALIDITY_RANGE_INVALID");
    }

    [Fact]
    public void Restore_RemainingStockExceedsTotal_ThrowsDomainException()
    {
        var action = () => VoucherDefinition.Restore(
            Guid.NewGuid(), "CODE", "Voucher", null, null,
            VoucherRewardTypes.Fixed, 10, VoucherValidityTypes.Fixed,
            DateTime.UtcNow, DateTime.UtcNow.AddDays(1), null,
            VoucherGenerationTypes.None, VoucherPublishTypes.Public,
            10, 11, DateTime.UtcNow, null);

        action.Should().Throw<DomainException>().Which.ErrorCode
            .Should().Be("VOUCHER_REMAINING_STOCK_INVALID");
    }

    private static VoucherDefinition CreatePublicVoucher() => VoucherDefinition.Create(
        " WELCOME10 ",
        " Welcome voucher ",
        " Description ",
        " https://example.com/banner.png ",
        " fixed ",
        10,
        " fixed ",
        DateTime.UtcNow,
        DateTime.UtcNow.AddDays(30),
        null,
        " none ",
        " public ",
        100);
}
