services:
  admin-api:
    container_name: loyalty-admin-api
    build:
      context: .
      dockerfile: api/admin/Dockerfile
    env_file:
      - api/admin/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "8081:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - loyalty_net

  customer-api:
    container_name: loyalty-customer-api
    build:
      context: .
      dockerfile: api/customer/Dockerfile
    env_file:
      - api/customer/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "8082:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - loyalty_net

  consumer:
    container_name: loyalty-consumer
    build:
      context: .
      dockerfile: worker/Consumer/Dockerfile
    env_file:
      - worker/Consumer/.env
    environment:
      DOTNET_ENVIRONMENT: Development
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - loyalty_net

  scheduler:
    container_name: loyalty-scheduler
    build:
      context: .
      dockerfile: worker/Scheduler/Dockerfile
    env_file:
      - worker/Scheduler/.env
    environment:
      DOTNET_ENVIRONMENT: Development
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - loyalty_net

  rabbitmq:
    container_name: loyalty-rabbitmq
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - loyalty_net

volumes:
  rabbitmq_data:

networks:
  loyalty_net:
    driver: bridge
