namespace Core.Entities.Constants;

public static class VoucherGenerationTypes
{
    public const string None = "NONE";
    public const string Imported = "IMPORTED";
    public const string AutoGenerated = "AUTO_GENERATED";

    public static bool IsDefined(string value)
    {
        var normalizedValue = Normalize(value);

        return normalizedValue is None or Imported or AutoGenerated;
    }

    public static string Normalize(string value)
    {
        return value.Trim().ToUpperInvariant();
    }
}
