namespace Core.Entities.Constants;

public static class VoucherGenerationTypes
{
    public const string None = "NONE";
    public const string Imported = "IMPORTED";
    public const string AutoGenerated = "AUTO_GENERATED";

    public static IReadOnlyList<string> All { get; } = new List<string>
    {
        None,
        Imported,
        AutoGenerated
    };

    public static bool IsDefined(string value)
    {
        var normalizedValue = Normalize(value);

        return All.Contains(normalizedValue);
    }

    public static string Normalize(string value)
    {
        return value.Trim().ToUpperInvariant();
    }
}
