using System.Text.Json;
using Core.Abstractions;
using Core.Entities;
using Core.Entities.Constants;
using Core.Exceptions;
using Core.UseCases.AuditLogs;
using Core.UseCases.VoucherDefinitions.Commands;
using Core.UseCases.VoucherDefinitions.Results;
using MediatR;

namespace Core.UseCases.VoucherDefinitions.Handlers;

public sealed class CreateVoucherDefinitionCommandHandler
    : IRequestHandler<CreateVoucherDefinitionCommand, VoucherDefinitionResult>
{
    private readonly IVoucherDefinitionRepository _voucherDefinitionRepository;
    private readonly IVoucherPoolProvisioningJobWriter _provisioningJobWriter;
    private readonly IAuditLogWriter _auditLogWriter;
    private readonly TimeProvider _timeProvider;

    public CreateVoucherDefinitionCommandHandler(
        IVoucherDefinitionRepository voucherDefinitionRepository,
        IVoucherPoolProvisioningJobWriter provisioningJobWriter,
        IAuditLogWriter auditLogWriter,
        TimeProvider timeProvider)
    {
        _voucherDefinitionRepository = voucherDefinitionRepository;
        _provisioningJobWriter = provisioningJobWriter;
        _auditLogWriter = auditLogWriter;
        _timeProvider = timeProvider;
    }

    public async Task<VoucherDefinitionResult> Handle(
        CreateVoucherDefinitionCommand request,
        CancellationToken ct)
    {
        var createdAt = _timeProvider.GetUtcNow().UtcDateTime;
        var voucherDefinition = VoucherDefinition.Create(
            request.Code,
            request.Name,
            request.Description,
            request.BannerImageUrl,
            request.RewardType,
            request.RewardValue,
            request.ValidityType,
            request.ValidFrom,
            request.ValidTo,
            request.DurationDay,
            request.GenerationType,
            request.PublishType,
            request.TotalStock,
            createdAt);

        if (voucherDefinition.Code is not null &&
            await _voucherDefinitionRepository.ExistsByCodeAsync(voucherDefinition.Code, ct))
        {
            throw new DomainException(
                "VOUCHER_CODE_ALREADY_EXISTS",
                DomainErrorType.Conflict);
        }

        var createdVoucherDefinition = _voucherDefinitionRepository.Add(voucherDefinition);
        VoucherPoolProvisioningJob? provisioningJob = null;

        if (createdVoucherDefinition.PublishType == VoucherPublishTypes.Private &&
            createdVoucherDefinition.GenerationType == VoucherGenerationTypes.AutoGenerated)
        {
            provisioningJob = VoucherPoolProvisioningJob.CreateAutoGenerated(
                createdVoucherDefinition.VoucherDefinitionId,
                createdVoucherDefinition.TotalStock,
                request.ActorUserId,
                createdAt);

            _provisioningJobWriter.Add(provisioningJob);
        }

        _auditLogWriter.Add(new AuditLogEntry(
            request.ActorUserId,
            AuditActions.Create,
            AuditEntityTypes.VoucherDefinition,
            createdVoucherDefinition.VoucherDefinitionId,
            null,
            JsonSerializer.Serialize(new
            {
                voucherDefinitionId = createdVoucherDefinition.VoucherDefinitionId,
                code = createdVoucherDefinition.Code,
                name = createdVoucherDefinition.Name,
                description = createdVoucherDefinition.Description,
                bannerImageUrl = createdVoucherDefinition.BannerImageUrl,
                rewardType = createdVoucherDefinition.RewardType,
                rewardValue = createdVoucherDefinition.RewardValue,
                validityType = createdVoucherDefinition.ValidityType,
                validFrom = createdVoucherDefinition.ValidFrom,
                validTo = createdVoucherDefinition.ValidTo,
                durationDay = createdVoucherDefinition.DurationDay,
                generationType = createdVoucherDefinition.GenerationType,
                publishType = createdVoucherDefinition.PublishType,
                totalStock = createdVoucherDefinition.TotalStock,
                remainingStock = createdVoucherDefinition.RemainingStock,
                provisioningJobId = provisioningJob?.JobId,
                provisioningStatus = provisioningJob?.Status,
                provisioningExpectedCount = provisioningJob?.ExpectedCount,
                createdAt = createdVoucherDefinition.CreatedAt
            }),
            null));

        return ToResult(createdVoucherDefinition, provisioningJob);
    }

    private static VoucherDefinitionResult ToResult(
        VoucherDefinition voucherDefinition,
        VoucherPoolProvisioningJob? provisioningJob)
    {
        return new VoucherDefinitionResult(
            voucherDefinition.VoucherDefinitionId,
            voucherDefinition.Code,
            voucherDefinition.Name,
            voucherDefinition.Description,
            voucherDefinition.BannerImageUrl,
            voucherDefinition.RewardType,
            voucherDefinition.RewardValue,
            voucherDefinition.ValidityType,
            voucherDefinition.ValidFrom,
            voucherDefinition.ValidTo,
            voucherDefinition.DurationDay,
            voucherDefinition.GenerationType,
            voucherDefinition.PublishType,
            voucherDefinition.TotalStock,
            voucherDefinition.RemainingStock,
            voucherDefinition.CreatedAt,
            voucherDefinition.DeletedAt,
            provisioningJob is null
                ? null
                : new VoucherPoolProvisioningResult(
                    provisioningJob.JobId,
                    provisioningJob.JobType,
                    provisioningJob.Status,
                    provisioningJob.ExpectedCount,
                    provisioningJob.ProcessedCount,
                    provisioningJob.AttemptCount,
                    null,
                    null,
                    provisioningJob.CreatedAt,
                    null,
                    null));
    }
}
