using System.Text.Json;
using Core.Abstractions;
using Core.Entities;
using Core.Entities.Constants;
using Core.Exceptions;
using Core.UseCases.AuditLogs;
using Core.UseCases.VoucherDefinitions.Commands;
using Core.UseCases.VoucherDefinitions.Results;
using MediatR;

namespace Core.UseCases.VoucherDefinitions.Handlers;

public sealed class CreateVoucherDefinitionCommandHandler
    : IRequestHandler<CreateVoucherDefinitionCommand, VoucherDefinitionResult>
{
    private const string AuditLogCreateAction = "CREATE";

    private readonly IVoucherDefinitionRepository _voucherDefinitionRepository;
    private readonly IAuditLogWriter _auditLogWriter;

    public CreateVoucherDefinitionCommandHandler(
        IVoucherDefinitionRepository voucherDefinitionRepository,
        IAuditLogWriter auditLogWriter)
    {
        _voucherDefinitionRepository = voucherDefinitionRepository;
        _auditLogWriter = auditLogWriter;
    }

    public async Task<VoucherDefinitionResult> Handle(
        CreateVoucherDefinitionCommand request,
        CancellationToken ct)
    {
        var voucherDefinition = VoucherDefinition.Create(
            request.Code,
            request.Name,
            request.Description,
            request.BannerImageUrl,
            request.RewardType,
            request.RewardValue,
            request.ValidityType,
            request.ValidFrom,
            request.ValidTo,
            request.DurationDay,
            request.GenerationType,
            request.PublishType,
            request.TotalStock);

        if (voucherDefinition.Code is not null &&
            await _voucherDefinitionRepository.ExistsByCodeAsync(voucherDefinition.Code, ct))
        {
            throw new DomainException(
                "VOUCHER_CODE_ALREADY_EXISTS",
                DomainErrorType.Conflict);
        }

        var createdVoucherDefinition = _voucherDefinitionRepository.Add(voucherDefinition);

        if (createdVoucherDefinition.PublishType == VoucherPublishTypes.Private &&
            createdVoucherDefinition.GenerationType == VoucherGenerationTypes.AutoGenerated)
        {
            // TODO: Generate TotalStock unique voucher codes and add their voucher_pool rows
        }

        _auditLogWriter.Add(new AuditLogEntry(
            request.ActorUserId,
            AuditLogCreateAction,
            AuditEntityTypes.VoucherDefinition,
            createdVoucherDefinition.VoucherDefinitionId,
            null,
            JsonSerializer.Serialize(new
            {
                voucherDefinitionId = createdVoucherDefinition.VoucherDefinitionId,
                code = createdVoucherDefinition.Code,
                name = createdVoucherDefinition.Name,
                description = createdVoucherDefinition.Description,
                bannerImageUrl = createdVoucherDefinition.BannerImageUrl,
                rewardType = createdVoucherDefinition.RewardType,
                rewardValue = createdVoucherDefinition.RewardValue,
                validityType = createdVoucherDefinition.ValidityType,
                validFrom = createdVoucherDefinition.ValidFrom,
                validTo = createdVoucherDefinition.ValidTo,
                durationDay = createdVoucherDefinition.DurationDay,
                generationType = createdVoucherDefinition.GenerationType,
                publishType = createdVoucherDefinition.PublishType,
                totalStock = createdVoucherDefinition.TotalStock,
                remainingStock = createdVoucherDefinition.RemainingStock,
                createdAt = createdVoucherDefinition.CreatedAt
            }),
            null));

        return ToResult(createdVoucherDefinition);
    }

    private static VoucherDefinitionResult ToResult(VoucherDefinition voucherDefinition)
    {
        return new VoucherDefinitionResult(
            voucherDefinition.VoucherDefinitionId,
            voucherDefinition.Code,
            voucherDefinition.Name,
            voucherDefinition.Description,
            voucherDefinition.BannerImageUrl,
            voucherDefinition.RewardType,
            voucherDefinition.RewardValue,
            voucherDefinition.ValidityType,
            voucherDefinition.ValidFrom,
            voucherDefinition.ValidTo,
            voucherDefinition.DurationDay,
            voucherDefinition.GenerationType,
            voucherDefinition.PublishType,
            voucherDefinition.TotalStock,
            voucherDefinition.RemainingStock,
            voucherDefinition.CreatedAt,
            voucherDefinition.DeletedAt);
    }
}
