<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Scheduler.Core</RootNamespace>
    <AssemblyName>Scheduler.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Messaging.Contracts\Messaging.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Campaign.Contracts\Campaign.Contracts.csproj" />
  </ItemGroup>
</Project>
