using Core.Entities.Constants;
using Core.Exceptions;

namespace Core.Entities;

public sealed class VoucherPoolProvisioningJob
{
    private VoucherPoolProvisioningJob(
        Guid jobId,
        Guid voucherDefinitionId,
        string jobType,
        int expectedCount,
        string status,
        Guid? createdBy,
        DateTime createdAt)
    {
        JobId = jobId;
        VoucherDefinitionId = voucherDefinitionId;
        JobType = jobType;
        ExpectedCount = expectedCount;
        Status = status;
        CreatedBy = createdBy;
        CreatedAt = createdAt;
    }

    public Guid JobId { get; }

    public Guid VoucherDefinitionId { get; }

    public string JobType { get; }

    public int ExpectedCount { get; }

    public int ProcessedCount => 0;

    public string Status { get; }

    public int AttemptCount => 0;

    public Guid? CreatedBy { get; }

    public DateTime CreatedAt { get; }

    public static VoucherPoolProvisioningJob CreateAutoGenerated(
        Guid voucherDefinitionId,
        int expectedCount,
        Guid? createdBy,
        DateTime createdAt)
    {
        if (voucherDefinitionId == Guid.Empty)
        {
            throw new DomainException(
                "VOUCHER_DEFINITION_ID_REQUIRED",
                DomainErrorType.Validation);
        }

        if (expectedCount <= 0 || expectedCount > VoucherDefinitionLimits.MaxTotalStock)
        {
            throw new DomainException(
                "VOUCHER_TOTAL_STOCK_INVALID",
                DomainErrorType.Validation);
        }

        return new VoucherPoolProvisioningJob(
            Guid.NewGuid(),
            voucherDefinitionId,
            VoucherPoolProvisioningJobTypes.AutoGenerated,
            expectedCount,
            VoucherPoolProvisioningJobStatuses.Pending,
            createdBy,
            createdAt);
    }
}
