using Core.Abstractions;
using Core.Entities;
using Core.Entities.Constants;
using Core.Exceptions;
using Core.Requests;
using MediatR;

namespace Core.Handlers;

public sealed class GenerateVoucherPoolBatchCommandHandler
    : IRequestHandler<GenerateVoucherPoolBatchCommand, GenerateVoucherPoolBatchResult>
{
    private readonly IVoucherPoolProvisioningRepository _repository;
    private readonly IVoucherPoolMutationStore _mutationStore;
    private readonly IVoucherCodeGenerator _codeGenerator;

    public GenerateVoucherPoolBatchCommandHandler(
        IVoucherPoolProvisioningRepository repository,
        IVoucherPoolMutationStore mutationStore,
        IVoucherCodeGenerator codeGenerator)
    {
        _repository = repository;
        _mutationStore = mutationStore;
        _codeGenerator = codeGenerator;
    }

    public async Task<GenerateVoucherPoolBatchResult> Handle(
        GenerateVoucherPoolBatchCommand request,
        CancellationToken cancellationToken)
    {
        if (request.JobId == Guid.Empty || request.BatchSize <= 0)
        {
            throw new VoucherPoolGenerationException(
                VoucherPoolGenerationErrorCodes.StateInvalid);
        }

        var job = await _repository.GetJobAsync(request.JobId, cancellationToken)
            ?? throw new VoucherPoolGenerationException(
                VoucherPoolGenerationErrorCodes.StateInvalid);

        if (job.JobType != VoucherPoolProvisioningJobTypes.AutoGenerated ||
            job.Status != VoucherPoolProvisioningJobStatuses.Processing ||
            job.ProcessedCount < 0 ||
            job.ProcessedCount > job.ExpectedCount)
        {
            throw new VoucherPoolGenerationException(
                VoucherPoolGenerationErrorCodes.StateInvalid);
        }

        var remaining = job.ExpectedCount - job.ProcessedCount;
        if (remaining == 0)
        {
            await _repository.ApplyProgressAsync(
                job.JobId,
                job.ProcessedCount,
                true,
                request.ProcessedAt,
                cancellationToken);

            return new GenerateVoucherPoolBatchResult(0, job.ProcessedCount, true);
        }

        var selectedCount = Math.Min(request.BatchSize, remaining);
        var codes = await GenerateUniqueCodesAsync(
            selectedCount,
            cancellationToken);
        var pools = codes
            .Select(code => new VoucherPoolMutation(
                Guid.NewGuid(),
                job.VoucherDefinitionId,
                code,
                VoucherPoolStatuses.Available,
                request.ProcessedAt))
            .ToArray();

        await _mutationStore.BulkInsertPoolsAsync(pools, cancellationToken);

        var processedCount = job.ProcessedCount + pools.Length;
        var completed = processedCount == job.ExpectedCount;
        await _repository.ApplyProgressAsync(
            job.JobId,
            processedCount,
            completed,
            request.ProcessedAt,
            cancellationToken);

        return new GenerateVoucherPoolBatchResult(
            pools.Length,
            processedCount,
            completed);
    }

    private async Task<IReadOnlyCollection<string>> GenerateUniqueCodesAsync(
        int count,
        CancellationToken cancellationToken)
    {
        var codes = new HashSet<string>(StringComparer.Ordinal);
        var generationAttempts = 0;
        var maximumGenerationAttempts =
            count * VoucherPoolGenerationLimits.MaxCollisionRounds * 2;

        for (var round = 0;
             round < VoucherPoolGenerationLimits.MaxCollisionRounds;
             round++)
        {
            while (codes.Count < count)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (generationAttempts++ >= maximumGenerationAttempts)
                {
                    throw new VoucherPoolGenerationException(
                        VoucherPoolGenerationErrorCodes.CodeCollision);
                }

                codes.Add(_codeGenerator.Generate());
            }

            var existingCodes = await _mutationStore.FindExistingCodesAsync(
                codes,
                cancellationToken);
            if (existingCodes.Count == 0)
            {
                return codes;
            }

            codes.ExceptWith(existingCodes);
        }

        throw new VoucherPoolGenerationException(
            VoucherPoolGenerationErrorCodes.CodeCollision);
    }
}
