using Core.Abstractions;
using Core.Entities.Constants;
using Core.Requests;
using MediatR;

namespace Core.Handlers;

public sealed class StartOrResumeVoucherPoolGenerationCommandHandler
    : IRequestHandler<StartOrResumeVoucherPoolGenerationCommand, StartOrResumeVoucherPoolGenerationResult>
{
    private const string PrivatePublishType = "PRIVATE";
    private readonly IVoucherPoolProvisioningRepository _repository;
    private readonly IVoucherPoolMutationStore _mutationStore;

    public StartOrResumeVoucherPoolGenerationCommandHandler(
        IVoucherPoolProvisioningRepository repository,
        IVoucherPoolMutationStore mutationStore)
    {
        _repository = repository;
        _mutationStore = mutationStore;
    }

    public async Task<StartOrResumeVoucherPoolGenerationResult> Handle(
        StartOrResumeVoucherPoolGenerationCommand request,
        CancellationToken cancellationToken)
    {
        var job = await _repository.GetNextAutoGeneratedJobAsync(cancellationToken);
        if (job is null)
        {
            return StartOrResumeVoucherPoolGenerationResult.NoWork;
        }

        var poolCount = await _mutationStore.CountPoolsAsync(
            job.VoucherDefinitionId,
            cancellationToken);
        var nextAttempt = job.AttemptCount + 1;
        var stateIsValid =
            job.JobType == VoucherPoolProvisioningJobTypes.AutoGenerated &&
            job.DefinitionGenerationType == VoucherPoolProvisioningJobTypes.AutoGenerated &&
            job.DefinitionPublishType == PrivatePublishType &&
            job.ExpectedCount == job.DefinitionTotalStock &&
            job.ProcessedCount >= 0 &&
            job.ProcessedCount <= job.ExpectedCount &&
            poolCount == job.ProcessedCount &&
            job.DefinitionRemainingStock == 0;

        if (!stateIsValid || nextAttempt > VoucherPoolGenerationLimits.MaxAttempts)
        {
            await _repository.RecordFailureAsync(
                job.JobId,
                VoucherPoolProvisioningJobStatuses.Failed,
                VoucherPoolGenerationErrorCodes.StateInvalid,
                null,
                request.StartedAt,
                cancellationToken);

            return new StartOrResumeVoucherPoolGenerationResult(
                false,
                job.JobId,
                job.ExpectedCount,
                job.ProcessedCount,
                true);
        }

        await _repository.MarkStartedAsync(
            job.JobId,
            nextAttempt,
            job.StartedAt ?? request.StartedAt,
            cancellationToken);

        return new StartOrResumeVoucherPoolGenerationResult(
            true,
            job.JobId,
            job.ExpectedCount,
            job.ProcessedCount,
            false);
    }
}
