using Core.Abstractions;
using Core.Entities.Constants;
using Core.Requests;
using MediatR;

namespace Core.Handlers;

public sealed class StartOrResumeVoucherPoolGenerationCommandHandler
    : IRequestHandler<StartOrResumeVoucherPoolGenerationCommand, StartOrResumeVoucherPoolGenerationResult>
{
    private const string PrivatePublishType = "PRIVATE";
    private readonly IVoucherPoolProvisioningRepository _repository;
    private readonly IVoucherPoolMutationStore _mutationStore;
    private readonly IVoucherPoolImportStore? _importStore;

    public StartOrResumeVoucherPoolGenerationCommandHandler(
        IVoucherPoolProvisioningRepository repository,
        IVoucherPoolMutationStore mutationStore,
        IVoucherPoolImportStore? importStore = null)
    {
        _repository = repository;
        _mutationStore = mutationStore;
        _importStore = importStore;
    }

    public async Task<StartOrResumeVoucherPoolGenerationResult> Handle(
        StartOrResumeVoucherPoolGenerationCommand request,
        CancellationToken cancellationToken)
    {
        var job = await _repository.GetNextProvisioningJobAsync(cancellationToken);
        if (job is null)
        {
            return StartOrResumeVoucherPoolGenerationResult.NoWork;
        }

        var poolCount = await _mutationStore.CountPoolsAsync(
            job.VoucherDefinitionId,
            cancellationToken);
        var stagedCount = job.JobType == VoucherPoolProvisioningJobTypes.Imported
            ? await (_importStore ?? throw new InvalidOperationException(
                    "Voucher pool import store is not configured."))
                .CountStagedRowsAsync(job.JobId, cancellationToken)
            : 0;
        var nextAttempt = job.AttemptCount + 1;
        var commonStateIsValid =
            job.ExpectedCount == job.DefinitionTotalStock &&
            job.ProcessedCount >= 0 &&
            job.ProcessedCount <= job.ExpectedCount &&
            job.DefinitionPublishType == PrivatePublishType &&
            job.DefinitionRemainingStock == 0;
        var autoGeneratedStateIsValid =
            job.JobType == VoucherPoolProvisioningJobTypes.AutoGenerated &&
            job.DefinitionGenerationType == VoucherPoolProvisioningJobTypes.AutoGenerated &&
            poolCount == job.ProcessedCount;
        var importedStateIsValid =
            job.JobType == VoucherPoolProvisioningJobTypes.Imported &&
            job.DefinitionGenerationType == VoucherPoolProvisioningJobTypes.Imported &&
            job.ExpectedCount <= VoucherPoolGenerationLimits.MaxImportedCount &&
            !string.IsNullOrWhiteSpace(job.ImportFileKey) &&
            poolCount == 0 &&
            stagedCount == job.ProcessedCount;
        var stateIsValid = commonStateIsValid &&
                           (autoGeneratedStateIsValid || importedStateIsValid);

        if (!stateIsValid || nextAttempt > VoucherPoolGenerationLimits.MaxAttempts)
        {
            await _repository.RecordFailureAsync(
                job.JobId,
                VoucherPoolProvisioningJobStatuses.Failed,
                job.JobType == VoucherPoolProvisioningJobTypes.Imported
                    ? VoucherPoolGenerationErrorCodes.ImportStateInvalid
                    : VoucherPoolGenerationErrorCodes.StateInvalid,
                null,
                request.StartedAt,
                cancellationToken);

            return new StartOrResumeVoucherPoolGenerationResult(
                false,
                job.JobId,
                job.ExpectedCount,
                job.ProcessedCount,
                true,
                job.JobType,
                job.ImportFileKey);
        }

        await _repository.MarkStartedAsync(
            job.JobId,
            nextAttempt,
            job.StartedAt ?? request.StartedAt,
            cancellationToken);

        return new StartOrResumeVoucherPoolGenerationResult(
            true,
            job.JobId,
            job.ExpectedCount,
            job.ProcessedCount,
            false,
            job.JobType,
            job.ImportFileKey);
    }
}
