using Core.Entities;

namespace Core.Abstractions;

public interface IVoucherPoolProvisioningRepository
{
    Task<VoucherPoolGenerationJob?> GetNextAutoGeneratedJobAsync(
        CancellationToken cancellationToken);

    Task<VoucherPoolGenerationJob?> GetJobAsync(
        Guid jobId,
        CancellationToken cancellationToken);

    Task MarkStartedAsync(
        Guid jobId,
        int attemptCount,
        DateTime startedAt,
        CancellationToken cancellationToken);

    Task ApplyProgressAsync(
        Guid jobId,
        int processedCount,
        bool completed,
        DateTime processedAt,
        CancellationToken cancellationToken);

    Task RecordFailureAsync(
        Guid jobId,
        string status,
        string errorCode,
        string? errorDetails,
        DateTime? completedAt,
        CancellationToken cancellationToken);
}
