using Core.Abstractions;
using Core.Entities;
using Core.Entities.Constants;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using NpgsqlTypes;
using Persistence.Models;
using Persistence.Models.Context;

namespace Infrastructure.Implementations;

public sealed class VoucherPoolProvisioningStore :
    IVoucherPoolProvisioningRepository,
    IVoucherPoolMutationStore
{
    private const string VoucherPoolCopyCommand =
        """
        COPY voucher_pools
            (voucher_pool_id, voucher_def_id, voucher_code, status, created_at)
        FROM STDIN (FORMAT BINARY)
        """;

    private readonly LoyaltyHubDbContext _dbContext;

    public VoucherPoolProvisioningStore(LoyaltyHubDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public Task<VoucherPoolGenerationJob?> GetNextAutoGeneratedJobAsync(
        CancellationToken cancellationToken)
    {
        return ProjectJobs()
            .Where(job =>
                job.JobType == VoucherPoolProvisioningJobTypes.AutoGenerated &&
                (job.Status == VoucherPoolProvisioningJobStatuses.Processing ||
                 job.Status == VoucherPoolProvisioningJobStatuses.Pending))
            .OrderBy(job =>
                job.Status == VoucherPoolProvisioningJobStatuses.Processing ? 0 : 1)
            .ThenBy(job => job.CreatedAt)
            .ThenBy(job => job.JobId)
            .Select(job => new VoucherPoolGenerationJob(
                job.JobId,
                job.VoucherDefId,
                job.JobType,
                job.ExpectedCount,
                job.ProcessedCount,
                job.Status,
                job.AttemptCount,
                job.VoucherDef.TotalStock,
                job.VoucherDef.RemainingStock,
                job.VoucherDef.GenerationType,
                job.VoucherDef.PublishType,
                job.StartedAt))
            .FirstOrDefaultAsync(cancellationToken);
    }

    public Task<VoucherPoolGenerationJob?> GetJobAsync(
        Guid jobId,
        CancellationToken cancellationToken)
    {
        return ProjectJobs()
            .Where(job => job.JobId == jobId)
            .Select(job => new VoucherPoolGenerationJob(
                job.JobId,
                job.VoucherDefId,
                job.JobType,
                job.ExpectedCount,
                job.ProcessedCount,
                job.Status,
                job.AttemptCount,
                job.VoucherDef.TotalStock,
                job.VoucherDef.RemainingStock,
                job.VoucherDef.GenerationType,
                job.VoucherDef.PublishType,
                job.StartedAt))
            .SingleOrDefaultAsync(cancellationToken);
    }

    public Task<int> CountPoolsAsync(
        Guid voucherDefinitionId,
        CancellationToken cancellationToken)
    {
        return _dbContext.VoucherPools
            .AsNoTracking()
            .CountAsync(
                pool => pool.VoucherDefId == voucherDefinitionId,
                cancellationToken);
    }

    public async Task<IReadOnlySet<string>> FindExistingCodesAsync(
        IReadOnlyCollection<string> voucherCodes,
        CancellationToken cancellationToken)
    {
        if (voucherCodes.Count == 0)
        {
            return new HashSet<string>(StringComparer.Ordinal);
        }

        var existingCodes = await _dbContext.VoucherPools
            .AsNoTracking()
            .Where(pool => voucherCodes.Contains(pool.VoucherCode))
            .Select(pool => pool.VoucherCode)
            .ToArrayAsync(cancellationToken);

        return existingCodes.ToHashSet(StringComparer.Ordinal);
    }

    public async Task MarkStartedAsync(
        Guid jobId,
        int attemptCount,
        DateTime startedAt,
        CancellationToken cancellationToken)
    {
        var job = await GetTrackedJobAsync(jobId, cancellationToken);
        job.Status = VoucherPoolProvisioningJobStatuses.Processing;
        job.AttemptCount = attemptCount;
        job.StartedAt ??= startedAt;
        job.ErrorCode = null;
        job.ErrorDetails = null;
        job.CompletedAt = null;
    }

    public async Task BulkInsertPoolsAsync(
        IReadOnlyCollection<VoucherPoolMutation> pools,
        CancellationToken cancellationToken)
    {
        if (pools.Count == 0)
        {
            return;
        }

        if (_dbContext.Database.CurrentTransaction is null)
        {
            throw new InvalidOperationException(
                "Voucher pool bulk insert requires an active database transaction.");
        }

        if (_dbContext.Database.GetDbConnection() is not NpgsqlConnection connection)
        {
            throw new InvalidOperationException(
                "Voucher pool bulk insert requires an Npgsql connection.");
        }

        await using var importer = await connection.BeginBinaryImportAsync(
            VoucherPoolCopyCommand,
            cancellationToken);

        foreach (var pool in pools)
        {
            await importer.StartRowAsync(cancellationToken);
            await importer.WriteAsync(
                pool.VoucherPoolId,
                NpgsqlDbType.Uuid,
                cancellationToken);
            await importer.WriteAsync(
                pool.VoucherDefinitionId,
                NpgsqlDbType.Uuid,
                cancellationToken);
            await importer.WriteAsync(
                pool.VoucherCode,
                NpgsqlDbType.Varchar,
                cancellationToken);
            await importer.WriteAsync(
                pool.Status,
                NpgsqlDbType.Varchar,
                cancellationToken);
            await importer.WriteAsync(
                pool.CreatedAt,
                NpgsqlDbType.TimestampTz,
                cancellationToken);
        }

        await importer.CompleteAsync(cancellationToken);
    }

    public async Task ApplyProgressAsync(
        Guid jobId,
        int processedCount,
        bool completed,
        DateTime processedAt,
        CancellationToken cancellationToken)
    {
        var job = await GetTrackedJobAsync(jobId, cancellationToken);
        job.ProcessedCount = processedCount;

        if (!completed)
        {
            return;
        }

        var definition = await _dbContext.VoucherDefinitions
            .SingleAsync(
                item => item.VoucherDefinitionId == job.VoucherDefId,
                cancellationToken);
        job.Status = VoucherPoolProvisioningJobStatuses.Completed;
        job.CompletedAt = processedAt;
        job.ErrorCode = null;
        job.ErrorDetails = null;
        definition.RemainingStock = definition.TotalStock;
    }

    public async Task RecordFailureAsync(
        Guid jobId,
        string status,
        string errorCode,
        string? errorDetails,
        DateTime? completedAt,
        CancellationToken cancellationToken)
    {
        var job = await GetTrackedJobAsync(jobId, cancellationToken);
        if (job.Status == VoucherPoolProvisioningJobStatuses.Completed)
        {
            return;
        }

        job.Status = status;
        job.ErrorCode = errorCode;
        job.ErrorDetails = errorDetails;
        job.CompletedAt = completedAt;
    }

    private IQueryable<VoucherPoolProvisioningJob> ProjectJobs()
    {
        return _dbContext.VoucherPoolProvisioningJobs.AsNoTracking();
    }

    private Task<VoucherPoolProvisioningJob> GetTrackedJobAsync(
        Guid jobId,
        CancellationToken cancellationToken)
    {
        return _dbContext.VoucherPoolProvisioningJobs
            .SingleAsync(job => job.JobId == jobId, cancellationToken);
    }
}
